// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace CNE.Entities.Entities
{
    public partial class tbAlcaldes
    {
        public tbAlcaldes()
        {
            tbVotos = new HashSet<tbVotos>();
        }

        public int Alc_Id { get; set; }
        public int? Alc_Votos { get; set; }
        public string Alc_ImgUrl { get; set; }
        public int Alc_UsuarioCreacion { get; set; }
        public DateTime Alc_FechaCreacion { get; set; }
        public int? Alc_UsuarioModificacion { get; set; }
        public DateTime? Alc_FechaModificacion { get; set; }
        public bool? Alc_Estado { get; set; }
      
        public int? Par_id { get; set; }
        [NotMapped]
        public string Par_ImgUrl { get; set; }
        [NotMapped]
        public string Per_Nombre { get; set; }
        [NotMapped]
        public string Per_Apellido { get; set; }
        public virtual tbPersonas Alc { get; set; }
        public virtual tbUsuarios Alc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Alc_UsuarioModificacionNavigation { get; set; }
        public virtual tbPartidos Par { get; set; }
        public virtual ICollection<tbVotos> tbVotos { get; set; }
    }
}