// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNE.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public int EsC_Id { get; set; }
        public string EsC_Descripcion { get; set; }
        public int EsC_UsuarioCreacion { get; set; }
        public DateTime EsC_FechaCreacion { get; set; }
        public int? EsC_UsuarioModificacion { get; set; }
        public DateTime? EsC_FechaModificacion { get; set; }
        public bool? EsC_Estado { get; set; }

        public virtual tbUsuarios EsC_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios EsC_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}