// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNE.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbCentrosVotaciones = new HashSet<tbCentrosVotaciones>();
            tbPersonas = new HashSet<tbPersonas>();
        }

        public string Mun_Id { get; set; }
        public string Mun_Descripcion { get; set; }
        public string Dep_Id { get; set; }
        public int Mun_UsuarioCreacion { get; set; }
        public DateTime Mun_FechaCreacion { get; set; }
        public int? Mun_UsuarioModificacion { get; set; }
        public DateTime? Mun_FechaModificacion { get; set; }
        public bool? Mun_Estado { get; set; }

        public virtual tbDepartamentos Dep { get; set; }
        public virtual tbUsuarios Mun_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Mun_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCentrosVotaciones> tbCentrosVotaciones { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}