// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNE.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsuar_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsuar_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbAlcaldesAlc_UsuarioCreacionNavigation = new HashSet<tbAlcaldes>();
            tbAlcaldesAlc_UsuarioModificacionNavigation = new HashSet<tbAlcaldes>();
            tbCentrosVotacionesCeV_UsuarioCreacionNavigation = new HashSet<tbCentrosVotaciones>();
            tbCentrosVotacionesCeV_UsuarioModificacionNavigation = new HashSet<tbCentrosVotaciones>();
            tbDepartamentosDep_UsuarioCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosDep_UsuarioModificacionNavigation = new HashSet<tbDepartamentos>();
            tbDiputadosDip_UsuarioCreacionNavigation = new HashSet<tbDiputados>();
            tbDiputadosDip_UsuarioModificacionNavigation = new HashSet<tbDiputados>();
            tbEmpleadosEmp_UsuarioCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosEmp_UsuarioModificacionNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivilesEsC_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEsC_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbMesasMes_UsuarioCreacionNavigation = new HashSet<tbMesas>();
            tbMesasMes_UsuarioModificacionNavigation = new HashSet<tbMesas>();
            tbMunicipiosMun_UsuarioCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosMun_UsuarioModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallasPanta_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPanta_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPapro_UsuarioCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPapro_UsuarioModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPartidosPar_UsuarioCreacionNavigation = new HashSet<tbPartidos>();
            tbPartidosPar_UsuarioModificacionNavigation = new HashSet<tbPartidos>();
            tbPersonasPer_UsuarioCreacionNavigation = new HashSet<tbPersonas>();
            tbPersonasPer_UsuarioModificacionNavigation = new HashSet<tbPersonas>();
            tbPresidentesPre_UsuarioCreacionNavigation = new HashSet<tbPresidentes>();
            tbPresidentesPre_UsuarioModificacionNavigation = new HashSet<tbPresidentes>();
            tbRolesRoles_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesRoles_UsuarioModificacionNavigation = new HashSet<tbRoles>();
        }

        public int Usuar_Id { get; set; }
        public string Usuar_Usuario { get; set; }
        public string Usuar_Contrasena { get; set; }
        public int Per_Id { get; set; }
        public int Roles_Id { get; set; }
        public DateTime? Usuar_UltimaSesion { get; set; }
        public bool? Usuar_Admin { get; set; }
        public int? Usuar_UsuarioCreacion { get; set; }
        public DateTime Usuar_FechaCreacion { get; set; }
        public int? Usuar_UsuarioModificacion { get; set; }
        public DateTime? Usuar_FechaModificacion { get; set; }
        public bool? Usuar_Estado { get; set; }

        public virtual tbEmpleados Per { get; set; }
        public virtual tbUsuarios Usuar_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Usuar_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsuar_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsuar_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbAlcaldes> tbAlcaldesAlc_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbAlcaldes> tbAlcaldesAlc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCentrosVotaciones> tbCentrosVotacionesCeV_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCentrosVotaciones> tbCentrosVotacionesCeV_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosDep_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosDep_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDiputados> tbDiputadosDip_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDiputados> tbDiputadosDip_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmp_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmp_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsC_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsC_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMesas> tbMesasMes_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMesas> tbMesasMes_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosMun_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosMun_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPanta_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPanta_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPapro_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPapro_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPartidos> tbPartidosPar_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPartidos> tbPartidosPar_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonasPer_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonasPer_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPresidentes> tbPresidentesPre_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPresidentes> tbPresidentesPre_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRoles_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRoles_UsuarioModificacionNavigation { get; set; }
    }
}