// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNE.Entities.Entities
{
    public partial class tbVotos
    {
        public tbVotos()
        {
            tbVotosPorDiputados = new HashSet<tbVotosPorDiputados>();
        }

        public int Vot_Id { get; set; }
        public int Mes_Id { get; set; }
        public int? Pre_Id { get; set; }
        public int? Alc_Id { get; set; }

        public virtual tbAlcaldes Alc { get; set; }
        public virtual tbMesas Mes { get; set; }
        public virtual tbPresidentes Pre { get; set; }
        public virtual ICollection<tbVotosPorDiputados> tbVotosPorDiputados { get; set; }
    }
}