// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNE.Entities.Entities
{
    public partial class tbVotosPorDiputados
    {
        public int VpD_Id { get; set; }
        public int Vot_Id { get; set; }
        public int Dip_Id { get; set; }

        public virtual tbDiputados Dip { get; set; }
        public virtual tbVotos Vot { get; set; }
    }
}